### ISSUE TITLE
possible workarounds on CentOS 7?

### ISSUE THREAD

**Issue by kclary** [toybox-rs/toybox-rs#36]
I have a script using `ctoybox` running on a server and get back this error with `native.so` when I try to install: 
```
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.7.4-1910/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.7.4-1910/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/server/user/project/demo.py", line 4, in <module>
    from toybox import Toybox, Input
  File "/server/user/project/venv/lib/python3.7/site-packages/toybox/__init__.py", line 1, in <module>
    import ctoybox
  File "/server/user/project/venv/lib/python3.7/site-packages/ctoybox/__init__.py", line 1, in <module>
    from .ffi import Toybox, State, Simulator
  File "/server/user/project/venv/lib/python3.7/site-packages/ctoybox/ffi.py", line 1, in <module>
    from .ctoybox import lib, ffi
  File "/server/user/project/venv/lib/python3.7/site-packages/ctoybox/ctoybox/__init__.py", line 6, in <module>
    lib = ffi.dlopen(os.path.join(os.path.dirname(__file__), 'native.so'), 4098)
OSError: cannot load library '/server/user/project/venv/lib/python3.7/site-packages/ctoybox/ctoybox/native.so': /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /server/user/project/venv/lib/python3.7/site-packages/ctoybox/ctoybox/native.so)
```

OS cannot find GLIBC_2.18 because it is CentOS 7, which will never upgrade beyond GLIBC_2.17 (and changing versions seems to be a Bad Idea anyhow). I found [this thread](https://stackoverflow.com/questions/55156942/deno-on-centos-7-glibc-2-18-not-found) that has some discussion and pointers to workarounds. One of them is [this issue](https://github.com/cdr/code-server/issues/1742), which suggests deleting any /lib64/\*.so.\*, which I don't think I can do. 

I have seen some workarounds mentioned [using Docker](https://github.com/cdr/code-server/issues/1742#issuecomment-635428464) / [example](https://github.com/hayd/deno-lambda/tree/master/example-docker-container). And others suggest to skip bundling dynamic libraries or use npm for installation because something something all native builds. Or [compiling on CentOS 7](https://github.com/cdr/code-server/releases/tag/v3.4.1). No idea if that is relevant, but I can try a local build there.

**Comment by kclary** [comment]
During local install following
```
cd ctoybox
cargo build
matruin develop --release
```

I get the following error: 

```
error[E0463]: can't find crate for `core` ] 0/76: adler32, bitflags...
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed


error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed


    Buildingerror[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed


    Building error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed


error: aborting due to previous error


error: aborting due to previous error


error: aborting due to previous error


error: aborting due to previous error


error: could not compile `itoa`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
  error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed


  Building [>                           ] 4/76: adler32, bitflags...error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed


error: aborting due to previous error


error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed


error: aborting due to previous error


error: aborting due to previous error


error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --target x86_64-unknown-linux-musl --lib --```

**Comment by jjfiv** [comment]
Seems like the workaround or fix here will be to run:

```
auditwheel repair *.wheel
```

I ran it on the manylinux1 image and that got @kclary unstuck; need to understand what's required there and get it into our release process in the future.

**Comment by jjfiv** [comment]
Popping my tabs here: 

 - https://github.com/nanoporetech/fast-ctc-decode/blob/b226ea0f2b2f4f474eff47349703d57d2ea4801b/.github/workflows/publish.yml
 - https://github.com/PyO3/maturin/issues/47

**Comment by kclary** [comment]
Building from a local wheel was a pretty good workaround! 

A bit of extra info- 
Per [this thread](https://www.reddit.com/r/rust/comments/cutwow/rust_musl_and_arch_linux/) I tried `rustup target add x86_64-unknown-linux-musl` and that satisfied musl. 

Now maturin fails to parse Cargo.toml: 
```
Caused by: missing field `package` at line 1 column 1
```

Could be wasm having a turn now? https://github.com/rustwasm/wasm-pack/issues/642

Not sure now that fits with the auditwheel fix

**Comment by etosch** [comment]
Any status updates on this?
